# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Casa di Shenbo
name: Shenbo Xuan
description: Your blog description
baseurl: "/blog"
url: "https://xuanshenbo.github.io"

# User settings
profile_img_url: http://materializecss.com/res/materialize.svg
username: xuanshenbo
user_description: Software developer based in New Zealand. I love AC Milan with all my heart.
email: xuanshenbo@hotmail.com
github_username: xuanshenbo
linkedin_username: xuanshenbo
disqus_username: xuanshenbo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins:
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# sass
sass:
  sass_dir: '_sass'
style: compressed

#links
links:
  - title: Home
    url: /home
    # external: true
  - title: Blog
    url: /
  - title: Tags
    url: /tags
